---
abstract: 'A complete GitLab API v3 client.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Log::Any::Adapter::TAP: v0.2.0
  Test::Simple: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GitLab-API-v3
requires:
  Const::Fast: '0'
  Log::Any: '0.11'
  Moo: '1.006000'
  Role::REST::Client: '0.18'
  Type::Tiny: '1'
  URI::Escape: '0'
  namespace::clean: '0'
  strictures: '0'
resources:
  bugtracker: https://github.com/bluefeet/GitLab-API-v3/issues
  homepage: https://github.com/bluefeet/GitLab-API-v3
  repository: https://github.com/bluefeet/GitLab-API-v3.git
version: '0.05'
